pushToS3:self.cdnUri value change
Error : 
---------------------------------------
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
---------------------------------------

endpoint value was giving just 's3.amazonaws.com'
client.endpoint change to client.urlBase;